FROM python:3.12-slim

WORKDIR /app

RUN pip install --no-cache-dir prometheus-client psutil

COPY Monitoring\ dan\ Logging/3.prometheus_exporter.py .

EXPOSE 8001

CMD ["python", "3.prometheus_exporter.py"]
